### ISSUE TITLE
Fresh install on a Ubuntu VM on a windows host.

### ISSUE THREAD

**Issue by marc-2019** [reality-two/reality2-node-core-elixir#24]
Hi Roy,

Attempted a fresh install on a VM on my Windows machine to try and prove my theory that there could be a memory leak? results of the fresh install below. Re the memory leak, it may not be Reality 2 but my Unbuntu runs for days without R2 running, if I R2 then at some point (usually while sleeping, but I'm guessing a couple of days in) the system hits a wall and either restarts or freezes (meaning I need to restart it). I'm running a node via docker on the hardware but nothing else, which makes me think it's R2?

marc@marc-Ubuntu:~/R2$ unzip x86_64_GNU_Linux.zip 
Archive:  x86_64_GNU_Linux.zip
   creating: x86_64_GNU_Linux/
  inflating: x86_64_GNU_Linux/reality2_0.1.11.tar.gz  
marc@marc-Ubuntu:~/R2$ cd x86_64_GNU_Linux/
marc@marc-Ubuntu:~/R2/x86_64_GNU_Linux$ tar -zxf reality2_0.1.11.tar.gz
marc@marc-Ubuntu:~/R2/x86_64_GNU_Linux$ cd reality2/
marc@marc-Ubuntu:~/R2/x86_64_GNU_Linux/reality2$ ls
bin  erts-15.0.1  extras  lib  releases  run
marc@marc-Ubuntu:~/R2/x86_64_GNU_Linux/reality2$ ./run
**************************************
Running: reality2 0.1.11
**************************************
[ai.reality2] started successfully.
[ai.reality2.web] started successfully.
[ai.reality2.data] started successfully.
[ai.reality2.geospatial] started successfully.
[ai.reality2.backup] started successfully.
[ai.reality2.rustdemo] started successfully.
11:58:40.962 [error] GenServer :tzdata_release_updater terminating
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a tuple

    :erlang.element(1, :error)
    (tzdata 1.1.1) lib/tzdata/util.ex:223: Tzdata.Util.to_int/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:38: Tzdata.Parser.process_rule/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
Last message: :check_if_time_to_update

**Comment by marc-2019** [comment]
Hold fire - I'm guessing it could be the cert as I missed that step from memory

**Comment by marc-2019** [comment]
marc@marc-Ubuntu:~/R2/x86_64_GNU_Linux/reality2$ ./run
**************************************
Running: reality2 0.1.11
**************************************
[ai.reality2] started successfully.
[ai.reality2.web] started successfully.
[ai.reality2.data] started successfully.
[ai.reality2.geospatial] started successfully.
[ai.reality2.backup] started successfully.
[ai.reality2.rustdemo] started successfully.
OS monotonic time stepped backwards!
Previous time: 82530786835526
Current time:  82530786787793
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[os_mon] memory supervisor port (memsup): Erlang has closed
./run: line 28: 19216 Aborted                 (core dumped) bin/reality2 start

**Comment by marc-2019** [comment]
Apparently we have a time paradox with my VM.

**Comment by reality2-roycdavies** [comment]
This will need some detective work.  I'll see if I can replicate the issue, and from there, see what it might depend on.

**Comment by reality2-roycdavies** [comment]
Also, did you have Sentants loaded to the Node?  If so, what?  Just as an aside, I have had 0.1.11 running on a Manjaro linux system for the last two weeks without any issues.
